#!/usr/bin/env python3
"""
Review Progress Tracker for Slovenian Translation

This script analyzes the sl.json5 file and generates a progress report
showing how many translations have been reviewed.

Usage: python scripts/review-progress.py
       python scripts/review-progress.py --json  (for JSON output)
"""

import sys
import re
import json
from pathlib import Path

# Path relative to project root
SCRIPT_DIR = Path(__file__).parent
PROJECT_ROOT = SCRIPT_DIR.parent
SL_PATH = PROJECT_ROOT / 'src' / 'assets' / 'i18n' / 'sl.json5'


def analyze_review_status(file_path):
    """
    Analyze review status markers in the translation file.

    Returns:
        dict: Statistics about review status
    """
    if not file_path.exists():
        print(f"❌ Error: File not found: {file_path}")
        print("\n💡 Hint: Run scripts/translate-sl.py first to generate the translation file")
        sys.exit(1)

    with open(file_path, 'r', encoding='utf-8') as f:
        content = f.read()

    # Count review status markers
    stats = {
        'pending': len(re.findall(r'// REVIEW: PENDING', content)),
        'done': len(re.findall(r'// REVIEW: DONE', content)),
        'needs_work': len(re.findall(r'// REVIEW: NEEDS_WORK', content)),
        'in_progress': len(re.findall(r'// REVIEW: IN_PROGRESS', content)),
    }

    stats['total'] = stats['pending'] + stats['done'] + stats['needs_work'] + stats['in_progress']

    if stats['total'] == 0:
        print('⚠️  Warning: No review markers found in file')
        print('   The file may not have been generated by translate-sl.py')
        return stats

    stats['percent_complete'] = (stats['done'] / stats['total'] * 100) if stats['total'] > 0 else 0

    return stats


def print_report(stats):
    """
    Print a formatted progress report.
    """
    print('\n╔════════════════════════════════════════════════════════════════╗')
    print('║       Slovenian Translation Review Progress Report            ║')
    print('╚════════════════════════════════════════════════════════════════╝\n')

    if stats['total'] == 0:
        print('No translation keys found with review markers.\n')
        return

    print(f"📊 Overall Progress: {stats['percent_complete']:.1f}% complete\n")

    # Progress bar
    bar_width = 50
    filled = int((stats['done'] / stats['total']) * bar_width)
    empty = bar_width - filled
    bar = '█' * filled + '░' * empty
    print(f"   [{bar}] {stats['done']}/{stats['total']}\n")

    # Detailed stats
    print('📈 Detailed Status:\n')
    print(f"   Total keys:       {stats['total']:>6}")
    print(f"   ✅ Done:          {stats['done']:>6} ({stats['done']/stats['total']*100:>5.1f}%)")
    print(f"   ⏳ Pending:       {stats['pending']:>6} ({stats['pending']/stats['total']*100:>5.1f}%)")
    print(f"   🔄 In Progress:   {stats['in_progress']:>6} ({stats['in_progress']/stats['total']*100:>5.1f}%)")
    print(f"   ⚠️  Needs Work:    {stats['needs_work']:>6} ({stats['needs_work']/stats['total']*100:>5.1f}%)")

    print('\n─────────────────────────────────────────────────────────────────\n')

    # Next steps
    if stats['done'] == stats['total']:
        print('🎉 Congratulations! All translations have been reviewed!\n')
    else:
        print('📝 Next Steps:\n')

        if stats['needs_work'] > 0:
            print(f'   1. Address {stats["needs_work"]} translation(s) that need work:')
            print(f'      grep -n "REVIEW: NEEDS_WORK" {SL_PATH}\n')

        if stats['in_progress'] > 0:
            print(f'   2. Complete {stats["in_progress"]} translation(s) in progress:')
            print(f'      grep -n "REVIEW: IN_PROGRESS" {SL_PATH}\n')

        if stats['pending'] > 0:
            step_num = 1 + (1 if stats['needs_work'] > 0 else 0) + (1 if stats['in_progress'] > 0 else 0)
            print(f'   {step_num}. Review {stats["pending"]} pending translation(s):')
            print(f'      grep -n "REVIEW: PENDING" {SL_PATH}\n')


def find_items_needing_attention(file_path, status='NEEDS_WORK'):
    """
    Find and list keys that need attention.
    """
    with open(file_path, 'r', encoding='utf-8') as f:
        lines = f.readlines()

    items = []

    for i, line in enumerate(lines):
        if f'REVIEW: {status}' in line:
            # Extract the key from this line
            key_match = re.search(r'"([^"]+)":', line)
            if key_match:
                key = key_match.group(1)

                # Extract any notes
                note_match = re.search(r'note:\s*([^}]+)', line)
                note = note_match.group(1).strip() if note_match else ''

                items.append({
                    'line': i + 1,
                    'key': key,
                    'note': note
                })

    return items


def main():
    """Main execution."""
    print(f"\nAnalyzing: {SL_PATH}\n")

    stats = analyze_review_status(SL_PATH)

    # Check for --json flag
    if '--json' in sys.argv:
        print(json.dumps(stats, indent=2))
        return

    print_report(stats)

    # If there are items needing work, list them
    if stats['needs_work'] > 0:
        print('⚠️  Items Needing Work:\n')
        items = find_items_needing_attention(SL_PATH, 'NEEDS_WORK')

        for item in items[:10]:
            print(f"   Line {item['line']}: {item['key']}")
            if item['note']:
                print(f"      Note: {item['note']}")

        if len(items) > 10:
            print(f"   ... and {len(items) - 10} more\n")
        else:
            print()


if __name__ == '__main__':
    try:
        main()
    except KeyboardInterrupt:
        print('\n')
        sys.exit(0)
